### ISSUE TITLE
create-cluster

### ISSUE THREAD

**Issue by hcltech84** [hcltech84/voting-app#1]
### Description

Create a standard, single-zone GKE cluster with HttpLoadBalancing add-on disabled

### Task list

- [ ] Install Google Cloud CLI or upgrade if already installed
- [ ] Initialize Google Cloud CLI
- [ ] Create a new Google Cloud project
- [ ] Enable Billing for new project
- [ ] Enable Kubernetes API for new project
- [ ] Create a standard, single-zone GKE cluster with HttpLoadBalancing add-on disabled
- [ ] Clean up
