### ISSUE TITLE
Setup Ingress Nginx

### ISSUE THREAD

**Issue by hcltech84** [hcltech84/voting-app#11]
### Task list

- [x] Install the Ingress Nginx Controller
- [x] Ingress configuration: switch from path based redirecting to host based redirecting
- [x] Fix error: result service can't connect to PostgreSQL
- [x] #12
